version: '3.8'
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    container_name: elastic
    environment:
      - node.name=elastic
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    expose:
      - 9200
    networks:
      - api_network_internal

  redis:
    container_name: redis_cache
    image: redis:6.2.6
    restart: always
    networks:
      - api_network_internal
    expose:
      - 6379
    volumes:
      - redis_data:/data

  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    image: api:latest
    pull_policy: never
    restart: always
    networks:
      - api_network_internal
      - api_network_external
    expose:
      - 8000
    depends_on:
      - elastic
      - redis
    env_file:
      - ./.env
    command: ["./wait-for-it.sh", "${ELASTIC_HOST}:9200", "--timeout=30", "--",
              "gunicorn", "main:app", "--workers", "4", "--worker-class",
              "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:8000"]

  nginx:
    container_name: nginx
    image: nginx:stable
    restart: always
    networks:
      - api_network_external
    ports:
      - 80:80
    volumes:
      - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./deploy/nginx/site.conf:/etc/nginx/conf.d/site.conf:ro
    depends_on:
      - api


volumes:
  es_data:
    name: es_volume
    driver: local
  redis_data:
    name: redis_volume

networks:
  api_network_external:
    driver: bridge
    name: api_network_external
  api_network_internal:
    driver: bridge
    name: api_network_internal